/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.2.1/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
    maven("https://maven.scijava.org/content/repositories/public/")
    
}

dependencies {

    testImplementation("org.junit.jupiter:junit-jupiter-api:5.8.1")
    testRuntimeOnly("org.junit.jupiter:junit-jupiter-engine:5.8.1")

    // This dependency is used by the application.
    implementation("com.google.guava:guava:31.1-jre")

    // HDF5 file handling
    // https://mvnrepository.com/artifact/cisd/jhdf5
    implementation("cisd:jhdf5:19.04.1")

    //FST - Fast Serialization
    // https://mvnrepository.com/artifact/de.ruedigermoeller/fst
    // Documentation: https://javadoc.io/doc/de.ruedigermoeller/fst/2.57/index.html
    // https://mvnrepository.com/artifact/de.ruedigermoeller/fst
    implementation("de.ruedigermoeller:fst:3.0.4-jdk17")

    // log4j 2 
    implementation("org.apache.logging.log4j:log4j-api:2.20.0")
    implementation("org.apache.logging.log4j:log4j-core:2.20.0")
    implementation("org.apache.logging.log4j:log4j-slf4j-impl:2.20.0")

}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(20))
    }
}

application {
    // Define the main class for the application.
    mainClass.set("lsh.App")
}

sourceSets {
    main {
        resources {
            exclude("**/*.ser")
            exclude("**/*.hdf5")
            exclude("**/*.properties")
        }
    }
}

tasks.jar {
    manifest.attributes["Main-Class"] = "lsh.App"
    val dependencies = configurations
        .runtimeClasspath
        .get()
        .map(::zipTree) // OR .map { zipTree(it) }
    from(dependencies)
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}

tasks.named<Test>("test") {
    useJUnitPlatform()
    testLogging {
		events("PASSED")
    }
}
